const express = require('express');
const eventsRouter = express.Router();

const Event = require('../models/Event');

eventsRouter.route('/')
  .get((req, res, next) => {
    Event.find({}, (err, events) => {
      if (err) { next(err) }
      else { res.send(events) }
    });
  });

eventsRouter.route('/:id')
  .get((req, res, next) => {
    // We expect the id to be the id generated by MongoDB, which means we 
    // can use the findById method.
    Event.findById(req.params.id, (err, event) => {
      if (err) { next(err) }
      // if event is not null, it has been found
      else if (event) { res.send(event) }
      // on the other hand, if it is null...
      else { res.sendStatus(404) }
    })
  });

// other useful routes
// find by year/month/day as path params
// find by keyword
// find by location
// find search?

module.exports = eventsRouter;